# Keras로 Linear&Logistic Regression 맛보기!

### Kaggle Link for exercise :
* [Digit Recognizer](https://www.kaggle.com/c/digit-recognizer) : 

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [2]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [3]:
x = np.array(range(0,20))
y = x * 2 -1 

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [4]:
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1) )

## 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,)) )

# 4번 컴파일 
model.compile(loss='mse',
              optimizer='adam')

In [5]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 369ms/step - loss: 187.2152
Epoch 2/10
1/1 [==============================] - 0s 4ms/step - loss: 186.8886
Epoch 3/10
1/1 [==============================] - 0s 5ms/step - loss: 186.5623
Epoch 4/10
1/1 [==============================] - 0s 7ms/step - loss: 186.2363
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 185.9106
Epoch 6/10
1/1 [==============================] - 0s 9ms/step - loss: 185.5852
Epoch 7/10
1/1 [==============================] - 0s 8ms/step - loss: 185.2602
Epoch 8/10
1/1 [==============================] - 0s 6ms/step - loss: 184.9354
Epoch 9/10
1/1 [==============================] - 0s 10ms/step - loss: 184.6110
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 184.2869


In [6]:
print(y)

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [11]:
y_pred = model.predict(x)

In [12]:
y_pred[:5].reshape(-1)

array([0.00999701, 0.7127328 , 1.4154686 , 2.118204  , 2.82094   ],
      dtype=float32)

In [10]:
y[:5].reshape(-1)

array([-1,  1,  3,  5,  7])

In [7]:
model.predict(x).reshape(-1)

array([9.9970084e-03, 7.1273279e-01, 1.4154686e+00, 2.1182041e+00,
       2.8209400e+00, 3.5236759e+00, 4.2264113e+00, 4.9291472e+00,
       5.6318831e+00, 6.3346190e+00, 7.0373549e+00, 7.7400904e+00,
       8.4428263e+00, 9.1455622e+00, 9.8482981e+00, 1.0551034e+01,
       1.1253770e+01, 1.1956506e+01, 1.2659242e+01, 1.3361978e+01],
      dtype=float32)

## Now, Your turn!

In [13]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [37]:
x.shape, y.shape

((20,), (20,))

In [14]:
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1) )

## 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,)) )

# 4번 컴파일 
model.compile(loss='mse',
              optimizer='adam')

In [33]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 9ms/step - loss: 258.7374
Epoch 2/10
1/1 [==============================] - 0s 5ms/step - loss: 258.3912
Epoch 3/10
1/1 [==============================] - 0s 5ms/step - loss: 258.0455
Epoch 4/10
1/1 [==============================] - 0s 7ms/step - loss: 257.7001
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 257.3552
Epoch 6/10
1/1 [==============================] - 0s 5ms/step - loss: 257.0106
Epoch 7/10
1/1 [==============================] - 0s 6ms/step - loss: 256.6664
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 256.3228
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 255.9794
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 255.6364


In [34]:
y_pred = model.predict(x)
y_pred[:5].reshape(-1)

array([-0.11753663, -0.9813243 , -1.8451121 , -2.7088997 , -3.5726874 ],
      dtype=float32)

In [35]:
y[:5].reshape(-1)

array([10,  7,  4,  1, -2])

In [36]:
model.predict(x).reshape(-1)

array([ -0.11753663,  -0.9813243 ,  -1.8451121 ,  -2.7088997 ,
        -3.5726874 ,  -4.4364753 ,  -5.300263  ,  -6.1640506 ,
        -7.027838  ,  -7.891626  ,  -8.755414  ,  -9.619202  ,
       -10.482989  , -11.346777  , -12.210565  , -13.074352  ,
       -13.93814   , -14.801928  , -15.665715  , -16.529503  ],
      dtype=float32)

## Quick Logistic Regression!

In [38]:
import tensorflow as tf
import tensorflow.keras as keras

import numpy as np

In [39]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [40]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# model에 순차적으로 레이어를 쌓아가겠다는 의도!
model = keras.models.Sequential()

# model에 인풋 값을 받는 레이어를 넣음
model.add( keras.layers.Input(shape=(1,)) )
# model에 Dense 레이어를 넣을거야 (최초의 레이어) : weight를 곱하고, bias를 더해주는 과정
model.add( keras.layers.Dense(1, activation='sigmoid') )


# 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,), activation='sigmoid') )

# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy',
              optimizer = 'adam',
              metrics=['accuracy'])

In [41]:
# 데이터를 넣어서 학습시키자!
model.fit(x[:15], y[:15], epochs=10, verbose=1)

# 결과 출력해줘!
print(y[15:])
print(model.predict(x[15:]))

Epoch 1/10
1/1 [==============================] - 1s 618ms/step - loss: 0.7560 - accuracy: 0.4000
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 0.7543 - accuracy: 0.4000
Epoch 3/10
1/1 [==============================] - 0s 6ms/step - loss: 0.7526 - accuracy: 0.4000
Epoch 4/10
1/1 [==============================] - 0s 7ms/step - loss: 0.7509 - accuracy: 0.4000
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 0.7492 - accuracy: 0.4000
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 0.7476 - accuracy: 0.4000
Epoch 7/10
1/1 [==============================] - 0s 8ms/step - loss: 0.7459 - accuracy: 0.4000
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 0.7443 - accuracy: 0.4000
Epoch 9/10
1/1 [==============================] - 0s 4ms/step - loss: 0.7427 - accuracy: 0.4000
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 0.7411 - accuracy: 0.4000
[1 1 1 1 1]
[[0.8512418 ]
 [0.8654520

In [42]:
y_pred = model.predict(x)

y_pred[:5].reshape(-1)

array([0.49750334, 0.5267172 , 0.55574924, 0.5844056 , 0.6125023 ],
      dtype=float32)

In [43]:
y[:5]

array([0, 0, 0, 0, 0])

## Now, Your turn!

In [44]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [46]:
keras.backend.clear_session()

model = keras.models.Sequential()

model.add(keras.layers.Input(shape = (1,)))
model.add(keras.layers.Dense(1, activation = 'sigmoid'))

model.compile(loss = 'binary_crossentropy',
             optimizer = 'adam',
             metrics=['accuracy'])

In [47]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
2/2 [==============================] - 0s 3ms/step - loss: 16.9292 - accuracy: 0.5000
Epoch 2/10
2/2 [==============================] - 0s 4ms/step - loss: 16.8999 - accuracy: 0.4750
Epoch 3/10
2/2 [==============================] - 0s 5ms/step - loss: 16.8680 - accuracy: 0.4750
Epoch 4/10
2/2 [==============================] - 0s 5ms/step - loss: 16.8395 - accuracy: 0.4750
Epoch 5/10
2/2 [==============================] - 0s 5ms/step - loss: 16.8082 - accuracy: 0.4750
Epoch 6/10
2/2 [==============================] - 0s 5ms/step - loss: 16.7794 - accuracy: 0.4750
Epoch 7/10
2/2 [==============================] - 0s 6ms/step - loss: 16.7484 - accuracy: 0.4750
Epoch 8/10
2/2 [==============================] - 0s 7ms/step - loss: 16.7175 - accuracy: 0.4750
Epoch 9/10
2/2 [==============================] - 0s 4ms/step - loss: 16.6890 - accuracy: 0.4750
Epoch 10/10
2/2 [==============================] - 0s 5ms/step - loss: 16.6575 - accuracy: 0.4750


In [48]:
y_pred = model.predict(x)

y_pred[:5].reshape(-1)

array([0.50497144, 0.2485494 , 0.09685966, 0.03360608, 0.01114991],
      dtype=float32)

In [49]:
y[:5]

array([0, 0, 0, 0, 0])