# Keras로 Linear&Logistic Regression 조금 더 맛보기

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

# Linear Regression on 쬐금 더 어려운 데이터

In [2]:
from sklearn.datasets import load_boston

In [3]:
boston = load_boston()

C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i

In [4]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [9]:
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add( keras.layers.Input(shape=(13,)) )
model.add( keras.layers.Dense(1) )

## 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(13,)) )

# 4번 컴파일 
model.compile(loss='mse',                #   loss = keras.losses.mean_squared_error
              optimizer='adam')          #   optimizer = keras.optimizers.Adam()


In [10]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 119870.3672
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 109944.6328
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 100622.3594
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 91894.5859
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 83727.0781
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 76167.1484
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 69144.6797
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 62640.2461
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 56599.3164
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 51143.9883


In [11]:
y_pred = model.predict(x)
y_pred[:5].reshape(-1)

array([-187.70201, -181.18973, -188.62508, -192.41537, -189.15085],
      dtype=float32)

In [12]:
y[:5].reshape(-1)

array([24. , 21.6, 34.7, 33.4, 36.2])

# Logistic Regression 쬐금 더 어려운 데이터

In [14]:
from sklearn.datasets import load_breast_cancer

In [15]:
cancer = load_breast_cancer()

In [18]:
x = cancer.data
y = cancer.target
x.shape, y.shape
# 모양 확인해볼 것

((569, 30), (569,))

In [21]:
keras.backend.clear_session()

model = keras.models.Sequential()

model.add(keras.layers.Input(shape = (30,)))
model.add(keras.layers.Dense(1, activation = 'sigmoid'))

model.compile(loss = 'binary_crossentropy',
             optimizer = 'adam',
             metrics=['accuracy'])

In [22]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
18/18 [==============================] - 0s 2ms/step - loss: 178.0808 - accuracy: 0.3726
Epoch 2/10
18/18 [==============================] - 0s 2ms/step - loss: 163.8217 - accuracy: 0.3726
Epoch 3/10
18/18 [==============================] - 0s 2ms/step - loss: 149.6758 - accuracy: 0.3726
Epoch 4/10
18/18 [==============================] - 0s 2ms/step - loss: 135.1841 - accuracy: 0.3726
Epoch 5/10
18/18 [==============================] - 0s 2ms/step - loss: 120.8881 - accuracy: 0.3726
Epoch 6/10
18/18 [==============================] - 0s 2ms/step - loss: 106.7640 - accuracy: 0.3726
Epoch 7/10
18/18 [==============================] - 0s 2ms/step - loss: 92.3306 - accuracy: 0.3726
Epoch 8/10
18/18 [==============================] - 0s 2ms/step - loss: 77.9065 - accuracy: 0.3726
Epoch 9/10
18/18 [==============================] - 0s 2ms/step - loss: 63.7194 - accuracy: 0.3726
Epoch 10/10
18/18 [==============================] - 0s 2ms/step - loss: 49.3302 - accuracy: 0.3743


In [25]:
y_pred = model.predict(x)
for idx, val in enumerate(y_pred):
    if val >= 0.5 :
        y_pred[idx] = 1
    else :
        y_pred[idx] = 0
y_pred[:5].reshape(-1)

array([0., 0., 0., 0., 0.], dtype=float32)

In [26]:
y[:5]

array([0, 0, 0, 0, 0])